apiVersion: v1
kind: Service
metadata:
  name: provider1-headless
  namespace: dapr-tests
  labels:
    app: provider1-headless
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: provider1-pod
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: provider1-statefulset
  namespace: dapr-tests
spec:
  serviceName: provider1-headless
  replicas: 2
  selector:
    matchLabels:
      app: provider1-pod
  template:
    metadata:
      labels:
        app: provider1-pod
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "provider1"
        dapr.io/app-port: "8080"
        dapr.io/sidecar-readiness-probe-threshold: "30"
        dapr.io/sidecar-liveness-probe-threshold: "30"
    spec:
      containers:
        - name: main
          image: edge-test-registry.cn-hangzhou.cr.aliyuncs.com/dapr/provider:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 10
